[package]
name = "planned-agent-ai-openai"
version = "0.1.0"
edition = "2021"

[dependencies]
planned-agent-core = { path = "../core" }
async-openai = { version = "0.41", features = ["chat-completion", "byot"] }
tokio.workspace = true
futures = "0.3"
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
async-trait.workspace = true
tracing.workspace = true
